services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - php
  mysql:
    image: mariadb:10.5
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html
    user: "${UID:-1000}:${GID:-1000}"
  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /var/www/html
  npm:
    image: node:18-alpine
    volumes:
      - ./src:/var/www/html
    entrypoint: ["/bin/sh", "-c"]
    working_dir: /var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - NODE_OPTIONS="--openssl-legacy-provider"
  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    entrypoint: ["php", "/var/www/html/artisan"]